// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtinygpu_top.h for the primary calling header

#ifndef VERILATED_VTINYGPU_TOP___024ROOT_H_
#define VERILATED_VTINYGPU_TOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtinygpu_top__Syms;

class Vtinygpu_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(mmio_valid,0,0);
        VL_IN8(mmio_we,0,0);
        VL_IN8(mmio_wstrb,3,0);
        VL_OUT8(mmio_ready,0,0);
        VL_OUT8(mem_req,0,0);
        VL_OUT8(mem_we,0,0);
        VL_OUT8(mem_wstrb,3,0);
        VL_IN8(mem_ready,0,0);
        VL_IN8(mem_rvalid,0,0);
        VL_OUT8(irq,0,0);
        CData/*0:0*/ tinygpu_top__DOT__reg_start_pulse;
        CData/*0:0*/ tinygpu_top__DOT__reg_soft_reset;
        CData/*0:0*/ tinygpu_top__DOT__reg_irq_enable;
        CData/*0:0*/ tinygpu_top__DOT__reg_direct_mode;
        CData/*7:0*/ tinygpu_top__DOT__reg_opcode;
        CData/*0:0*/ tinygpu_top__DOT__ctrl_busy;
        CData/*0:0*/ tinygpu_top__DOT__ctrl_done;
        CData/*0:0*/ tinygpu_top__DOT__ctrl_illegal_opcode;
        CData/*0:0*/ tinygpu_top__DOT__ctrl_shape_error;
        CData/*0:0*/ tinygpu_top__DOT__ctrl_memory_error;
        CData/*0:0*/ tinygpu_top__DOT__ctrl_unsupported_format;
        CData/*0:0*/ tinygpu_top__DOT__cnt_cmd_start;
        CData/*0:0*/ tinygpu_top__DOT__cnt_cmd_done;
        CData/*0:0*/ tinygpu_top__DOT__cnt_stall;
        CData/*0:0*/ tinygpu_top__DOT__mem_req_raw;
        CData/*0:0*/ tinygpu_top__DOT__mem_rvalid_stage_q;
        CData/*0:0*/ tinygpu_top__DOT__mem_cmd_valid_q;
        CData/*0:0*/ tinygpu_top__DOT__mem_cmd_we_q;
        CData/*3:0*/ tinygpu_top__DOT__mem_cmd_wstrb_q;
        CData/*0:0*/ tinygpu_top__DOT__mem_read_pending_q;
        CData/*0:0*/ tinygpu_top__DOT__mem_stage_ready;
        CData/*0:0*/ tinygpu_top__DOT__u_regs__DOT__done_sticky_q;
        CData/*0:0*/ tinygpu_top__DOT__u_regs__DOT__irq_pending_q;
        CData/*4:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__state_q;
        CData/*4:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__state_d;
        CData/*7:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__opcode_q;
        CData/*4:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__desc_word_idx_q;
        CData/*4:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__desc_word_idx_d;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__store_stage_done_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__store_stage_done_d;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_inflight_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_inflight_d;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_inflight_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_inflight_d;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_inflight_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_inflight_d;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__desc_inflight_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__desc_inflight_d;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__row_mask;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__col_mask;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__array_clear_acc;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__array_mac_en;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__spm_dma_wr_en;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__spm_dma_region;
        CData/*3:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__spm_dma_wstrb;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__c_wr_en;
        CData/*7:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__c_wr_addr;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__epi_start;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__epi_busy;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__epi_done;
        CData/*7:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_x_q;
        CData/*7:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_y_q;
    };
    struct {
        CData/*7:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_result_i8;
        CData/*3:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_store_wstrb_q;
        CData/*7:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_result_i8_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_start;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_busy;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_mem_req;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_mem_we;
        CData/*3:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_mem_wstrb;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_mem_req;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_mem_req;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_mem_we;
        CData/*3:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_mem_wstrb;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__desc_mem_req;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_launch_pending_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_launch_pending_d;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_op_kind_q;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_spm_region_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__latch_cmd;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__latch_cmd_addr;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__clear_cmd_fields;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__load_desc_word;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__latch_vec_store_cmd;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__latch_dma_cmd;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__clear_status;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__set_illegal_opcode;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__set_shape_error;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__set_memory_error;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__set_unsupported_format;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__opcode_ok;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_flags_ok;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dims_ok;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__more_k_tiles;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__store_stage_last;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__clear_bias_regs;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__load_bias_reg;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__load_vec_x_reg;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__load_vec_y_reg;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__is_vector_opcode_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__state_is_vec;
        CData/*7:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_load_byte;
        CData/*3:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_store_wstrb_next;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_op_kind_cmd_n;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_spm_region_cmd_n;
        CData/*2:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__state_q;
        CData/*2:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__state_d;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__done_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__error_q;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__op_kind_q;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__spm_region_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__advance_elem;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__last_elem;
        CData/*1:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__state_q;
        CData/*0:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__valid_elem;
        CData/*0:0*/ __Vclklast__TOP__clk;
        CData/*0:0*/ __Vclklast__TOP__rst_n;
        SData/*15:0*/ tinygpu_top__DOT__reg_dim_m;
        SData/*15:0*/ tinygpu_top__DOT__reg_dim_n;
        SData/*15:0*/ tinygpu_top__DOT__reg_dim_k;
        SData/*15:0*/ tinygpu_top__DOT__reg_stride0;
        SData/*15:0*/ tinygpu_top__DOT__reg_stride1;
        SData/*15:0*/ tinygpu_top__DOT__reg_stride_dst;
        SData/*15:0*/ tinygpu_top__DOT__reg_shift;
        SData/*15:0*/ tinygpu_top__DOT__reg_zero_point;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__M_q;
    };
    struct {
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__N_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__K_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__stride0_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__stride1_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__stride_dst_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__shift_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__zero_point_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__m0_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__m0_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__n0_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__n0_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__k0_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__k0_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__kk_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__kk_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__store_row_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__store_row_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__store_col_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__store_col_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_col_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_col_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_idx_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_idx_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__active_tile_m;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__active_tile_n;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__active_tile_k;
        SData/*8:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__spm_dma_addr;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_rows_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_cols_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_stride_bytes_q;
        SData/*8:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_spm_base_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__effective_n_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_rows_cmd_n;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_cols_cmd_n;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_stride_bytes_cmd_n;
        SData/*8:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_spm_base_cmd_n;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__rows_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__cols_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__stride_bytes_q;
        SData/*8:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__spm_base_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__row_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__row_d;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__col_q;
        SData/*15:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__col_d;
        VL_IN(mmio_addr,31,0);
        VL_IN(mmio_wdata,31,0);
        VL_OUT(mmio_rdata,31,0);
        VL_OUT(mem_addr,31,0);
        VL_OUT(mem_wdata,31,0);
        VL_IN(mem_rdata,31,0);
        IData/*31:0*/ tinygpu_top__DOT__reg_cmd_addr;
        IData/*31:0*/ tinygpu_top__DOT__reg_src0_addr;
        IData/*31:0*/ tinygpu_top__DOT__reg_src1_addr;
        IData/*31:0*/ tinygpu_top__DOT__reg_bias_addr;
        IData/*31:0*/ tinygpu_top__DOT__reg_dst_addr;
        IData/*31:0*/ tinygpu_top__DOT__reg_flags;
        IData/*31:0*/ tinygpu_top__DOT__reg_scale;
        IData/*31:0*/ tinygpu_top__DOT__cycle_count_last;
        IData/*31:0*/ tinygpu_top__DOT__active_count_last;
        IData/*31:0*/ tinygpu_top__DOT__stall_count_last;
        IData/*31:0*/ tinygpu_top__DOT__cmd_count_total;
        IData/*31:0*/ tinygpu_top__DOT__mem_rdata_stage_q;
        IData/*31:0*/ tinygpu_top__DOT__mem_cmd_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__mem_cmd_wdata_q;
    };
    struct {
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__ctrl_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__direct_op_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__dim_m_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__dim_n_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__dim_k_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__stride0_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__stride1_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__stride_dst_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_regs__DOT__shiftzp_next_w;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__flags_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__cmd_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src0_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src1_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__scale_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__spm_dma_wdata;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__spm_dma_rdata;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__c_wr_data;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_result_raw;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_result_post;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_store_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_store_wdata_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_result_raw_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_result_post_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_scaled_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_mem_addr;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_mem_wdata;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_mem_addr;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_mem_wdata;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_base_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src0_row_base_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src0_row_base_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src1_k_base_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src1_k_base_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src1_n_offset_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src1_n_offset_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_row_base_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_row_base_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_n_offset_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_n_offset_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_base_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_base_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src0_m_step_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__src0_m_step_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__stride1_k_step_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__stride1_k_step_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_m_step_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_m_step_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_n_step_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dst_n_step_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_n_step_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_n_step_d;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_src0_elem_addr;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_src1_elem_addr;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_dst_elem_addr;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__vec_store_wdata_next;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__dma_base_addr_cmd_n;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__unnamedblk2__DOT__c;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__unnamedblk3__DOT__c;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__unnamedblk1__DOT__c;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_spm__DOT__unnamedblk4__DOT__byte_idx;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_spm__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_spm__DOT__unnamedblk2__DOT__i;
    };
    struct {
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_spm__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__base_addr_q;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__elem_addr;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__write_addr;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_dma__DOT__spm_addr_store_i32;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_array4x4__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_o;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_array4x4__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_o;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_array4x4__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc_o;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_array4x4__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc_o;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk3__DOT__r;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk3__DOT__unnamedblk4__DOT__c;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk3__DOT__unnamedblk4__DOT__unnamedblk5__DOT__x_post;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk6__DOT__r;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk6__DOT__unnamedblk7__DOT__c;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk8__DOT__r;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk8__DOT__unnamedblk9__DOT__c;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk8__DOT__unnamedblk9__DOT__unnamedblk10__DOT__x_shifted;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk1__DOT__r;
        IData/*31:0*/ tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__unnamedblk1__DOT__unnamedblk2__DOT__c;
        IData/*31:0*/ tinygpu_top__DOT__u_counters__DOT__cycle_cur_q;
        IData/*31:0*/ tinygpu_top__DOT__u_counters__DOT__active_cur_q;
        IData/*31:0*/ tinygpu_top__DOT__u_counters__DOT__stall_cur_q;
        IData/*31:0*/ __Vfunc_tinygpu_top__DOT__u_cmd_ctrl__DOT__clamp32__16__Vfuncout;
        IData/*31:0*/ __Vfunc_tinygpu_top__DOT__u_cmd_ctrl__DOT__clamp32__16__x;
        IData/*31:0*/ __Vfunc_tinygpu_top__DOT__u_cmd_ctrl__DOT__u_vec_alu__DOT__clamp32__28__Vfuncout;
        IData/*31:0*/ __Vfunc_tinygpu_top__DOT__u_cmd_ctrl__DOT__u_vec_alu__DOT__clamp32__28__x;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__a_rd_addr;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__a_rd_data;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__b_rd_addr;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__b_rd_data;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__a_vec;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__b_vec;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__c_tile;
        VlUnpacked<IData/*31:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__bias_vec;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__c_epi_i32;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__c_epi_i8;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellout__u_spm__b_rd_data;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellinp__u_spm__b_rd_addr;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellout__u_spm__a_rd_data;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellinp__u_spm__a_rd_addr;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellout__u_array4x4__c_tile;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellinp__u_array4x4__b_vec;
        VlUnpacked<CData/*7:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellinp__u_array4x4__a_vec;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellout__u_epilogue__c_out_i8;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellout__u_epilogue__c_out_i32;
        VlUnpacked<IData/*31:0*/, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellinp__u_epilogue__bias;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT____Vcellinp__u_epilogue__c_in;
        VlUnpacked<CData/*7:0*/, 256> tinygpu_top__DOT__u_cmd_ctrl__DOT__u_spm__DOT__a_mem;
        VlUnpacked<CData/*7:0*/, 256> tinygpu_top__DOT__u_cmd_ctrl__DOT__u_spm__DOT__b_mem;
        VlUnpacked<CData/*7:0*/, 128> tinygpu_top__DOT__u_cmd_ctrl__DOT__u_spm__DOT__c_mem;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__post_q;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 2>, 2> tinygpu_top__DOT__u_cmd_ctrl__DOT__u_epilogue__DOT__scaled_q;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vtinygpu_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtinygpu_top___024root(Vtinygpu_top__Syms* symsp, const char* name);
    ~Vtinygpu_top___024root();
    VL_UNCOPYABLE(Vtinygpu_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
